### ISSUE TITLE
kubepug not found in repository

### ISSUE THREAD

**Issue by bcdady** [s3than/asdf-kubepug#1]
`asdf plugin add kubepug` doesn't work

**Describe the solution you'd like**

Instructions in the README should work reliably.

For this case, it's probably just easiest to remove that simpler version of the asdf command from the README

**Describe alternatives you've considered**

Work with asdf-community to get kubepug plugin included in [asdf-community](https://github.com/asdf-community/)

Example:
```sh
❯ asdf plugin add kubepug
plugin kubepug not found in repository

❯ asdf version
v0.10.2
```

**Comment by s3than** [comment]
@bcdady Thanks for the feedback, sorry it took so long to get back to this.. I've updated and removed that line from the Readme.
